#******************************************************************************
# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#*****************************************************************************

Import('services_common_env')

srcs = services_common_env.Glob('*.cc')

libs = []

# Static library
objs = services_common_env.Object(srcs)
libs.append(services_common_env.StaticLibrary('alljoyn_services_common', objs))

# Shared library
if services_common_env.get('LIBTYPE', 'static') != 'static':
    shobjs = services_common_env.SharedObject(srcs)
    libs.append(services_common_env.SharedLibrary('alljoyn_services_common', shobjs))

Return('libs')