#******************************************************************************
# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#*****************************************************************************

Import('cpsenv')

srcs = cpsenv.Glob('*.cc')
srcs += cpsenv.Glob('Widgets/*.cc')
srcs += cpsenv.Glob('BusObjects/*.cc')

libs = []

# Static library
objs = cpsenv.Object(srcs)
libs.append(cpsenv.StaticLibrary('alljoyn_controlpanel', objs))

# Shared library
if cpsenv.get('LIBTYPE', 'static') != 'static':
    shobjs = cpsenv.SharedObject(srcs)
    libs.append(cpsenv.SharedLibrary('alljoyn_controlpanel', shobjs))

Return('libs')