# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('config_env')

if config_env.has_key('_ALLJOYN_JAVA_'):
    config_env.Append(JAVACLASSPATH = [ str(config_env.File('$DISTDIR/java/jar/alljoyn.jar')),
                                        str(config_env.File('$DISTDIR/java/jar/alljoyn_about.jar')) ])
    config_env['dep_jars'] = [ '$DISTDIR/java/jar/alljoyn.jar',
                               '$DISTDIR/java/jar/alljoyn_about.jar' ]
else:
    config_env.Append(JAVACLASSPATH = [ str(config_env.File('$ALLJOYN_DISTDIR/java/jar/alljoyn.jar')),
                                        str(config_env.File('$ALLJOYN_DISTDIR/java/jar/alljoyn_about.jar')) ])
    config_env['dep_jars'] = [ ]

jars = []
jars += config_env.SConscript('src/SConscript', exports = ['config_env']),
if config_env['BUILD_SERVICES_SAMPLES'] == 'on':
    jars += config_env.SConscript('samples/SConscript', exports = ['config_env'])

config_env.Install('$DISTDIR/config/jar', jars)