#******************************************************************************
# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0

#*****************************************************************************

import os
Import('tsenv')
Import('env')

src  =  tsenv.Glob('*.cc')
src += tsenv.Glob('client/*.cc')
src += tsenv.Glob('common/*.cc')
src += tsenv.Glob('server/*.cc')

libs = []


tsenv.Append(CPPPATH = ['$LIBXML2_INCLUDE','$LIBICONV_INCLUDE'])
tsenv.Append(LIBS = ['libxml2'])
tsenv.Append(LIBPATH = ['$LIBXML2_PATH'])


# Static library
objs = tsenv.Object(src)
libs.append(tsenv.StaticLibrary('alljoyn_time', objs))

# Shared library
if tsenv.get('LIBTYPE', 'static') != 'static':
    shobjs = tsenv.SharedObject(src)
    libs.append(tsenv.SharedLibrary('alljoyn_time', shobjs))

Return('libs')