# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('cpsenv')

if not cpsenv.has_key('_ALLJOYNCORE_'):
    cpsenv.Append(LIBS = ['alljoyn'])
    if cpsenv['BR'] == 'on' :
        brFile = cpsenv.subst('$DISTDIR') + '/cpp/lib/BundledRouter.o'
        cpsenv['brobj'] = File(brFile)
        cpsenv['ajrlib'] = 'ajrouter'
    if cpsenv['OS'] == 'openwrt':
        cpsenv.AppendUnique(LIBS = [ 'stdc++', 'pthread' ])

cpsenv['CPS_DISTDIR'] = cpsenv['DISTDIR'] + '/controlpanel'

cpsenv.Install('$CPS_DISTDIR/inc/alljoyn/controlpanel', cpsenv.Glob('inc/alljoyn/controlpanel/*.h'))
cpsenv.Install('$CPS_DISTDIR/lib', cpsenv.SConscript('src/SConscript', exports = ['cpsenv']))
if cpsenv['BUILD_SERVICES_SAMPLES'] == 'on':
    cpsenv.Install('$CPS_DISTDIR/bin', cpsenv.SConscript('samples/SConscript', exports = ['cpsenv']))

# Build docs
installDocs = cpsenv.SConscript('docs/SConscript', exports = ['cpsenv'])
cpsenv.Depends(installDocs, cpsenv.Glob('$CPS_DISTDIR/inc/alljoyn/controlpanel/*.h'));