# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('onb_env')

# Sources
srcs = onb_env.Glob('*.cc')

# Platform specific sources
if onb_env['OS'] == 'android':
    srcs += onb_env.Glob('$OS/*.cc')
else:
    srcs += onb_env.Glob('$OS_GROUP/*.cc')

libs = []

# Static library
objs = onb_env.Object(srcs)
libs.append(onb_env.StaticLibrary('alljoyn_onboarding', objs))

# Shared library
if onb_env.get('LIBTYPE', 'static') != 'static':
    shobjs = onb_env.SharedObject(srcs)
    libs.append(onb_env.SharedLibrary('alljoyn_onboarding', shobjs))

Return ('libs')