# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0



Import('server_sample_env')

if not server_sample_env.has_key('_ALLJOYNCORE_'):
    server_sample_env.Append(LIBS = ['alljoyn'])
    if server_sample_env['BR'] == 'on' :
        brFile = server_sample_env.subst('$DISTDIR') + '/cpp/lib/BundledRouter.o'
        server_sample_env['brobj'] = File(brFile)
        server_sample_env['ajrlib'] = 'ajrouter'
    if server_sample_env['OS'] == 'openwrt':
        server_sample_env.AppendUnique(LIBS = [ 'stdc++', 'pthread' ])

# Make serversample dist a sub-directory of the alljoyn dist.  This avoids any conflicts with alljoyn dist targets.
server_sample_env['SAMPLE_APPS_DISTDIR'] = server_sample_env['DISTDIR'] + '/sample_apps'

# Sample programs
if server_sample_env['BUILD_SERVICES_SAMPLES'] == 'on':
    server_sample_env.Install('$SAMPLE_APPS_DISTDIR/bin', server_sample_env.SConscript('samples/SConscript', exports = ['server_sample_env']))

# Build docs
installDocs = server_sample_env.SConscript('docs/SConscript', exports = ['server_sample_env'])
server_sample_env.Depends(installDocs, server_sample_env.Glob('$ONBOARDING_DISTDIR/inc/alljoyn/onboarding/*.h'));