# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


import os

Import('env')

env['_ALLJOYN_SERVICES_COMMON_'] = True
env['OBJDIR_SERVICES_COMMON'] = env['OBJDIR'] + '/services/common'

# Make config library and header file paths available to the global environment
env.Append(LIBPATH = '$DISTDIR/services_common/lib');
env.Append(CPPPATH = '$DISTDIR/services_common/inc');

services_common_env = env.Clone()

for b in services_common_env['bindings']:
    if os.path.exists('%s/SConscript' % b):
        services_common_env.VariantDir('$OBJDIR_SERVICES_COMMON/%s' % b, b, duplicate = 0)

services_common_env.SConscript(['$OBJDIR_SERVICES_COMMON/%s/SConscript' % b for b in env['bindings'] if os.path.exists('%s/SConscript' % b) ],
                      exports = ['services_common_env'])
