# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


Import('services_common_env')
 
if not services_common_env.has_key('_ALLJOYNCORE_'):
    services_common_env.Append(LIBS = ['alljoyn'])
    if services_common_env['OS'] == 'openwrt':
        services_common_env.AppendUnique(LIBS = [ 'stdc++', 'pthread' ])

services_common_env['SC_DISTDIR'] = services_common_env['DISTDIR'] + '/services_common'

services_common_env.Install('$SC_DISTDIR/inc/alljoyn/services_common', services_common_env.Glob('inc/alljoyn/services_common/*.h'))
services_common_env.Install('$SC_DISTDIR/lib', services_common_env.SConscript('src/SConscript', exports = ['services_common_env']))

# Build docs
installDocs = services_common_env.SConscript('docs/SConscript', exports = ['services_common_env'])
services_common_env.Depends(installDocs, services_common_env.Glob('$SC_DISTDIR/inc/alljoyn/services_common/*.h'));