# # 
#    Copyright (c) 2016 Open Connectivity Foundation and AllJoyn Open
#    Source Project Contributors and others.
#    
#    All rights reserved. This program and the accompanying materials are
#    made available under the terms of the Apache License, Version 2.0
#    which accompanies this distribution, and is available at
#    http://www.apache.org/licenses/LICENSE-2.0


import os
Import('env')

returnValue = []

docenv = env.Clone()

# Build docs
if docenv['DOCS'] == 'html':
    # the target directory 'docs/tmp' is never built this will cause doxygen 
    # to run every time DOCS == 'html'
    generateDocs = docenv.Doxygen(source='Doxygen_html', target=[Dir('tmp'), Dir('html')])
    returnValue = docenv.Install('$NS_DIST_DIR/docs', Dir('html'))
    docenv.Clean('Doxygen_html', Dir('html'))
    docenv.Depends(returnValue, generateDocs)

Return('returnValue')